services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda
      - GATEWAY_LISTEN=0.0.0.0:4566
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/docker-entrypoint-initaws.d"
      - /var/run/docker.sock:/var/run/docker.sock
