[project]
name = "bingomaker"
version = "0.1.0"
description = "A multiplayer bingo game maker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.35.50",
    "flask>=3.0.3",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
    "ruff>=0.7.1",
]
