name: Test python

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  push:
    branches:
      '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: 'latest'
          install-awslocal: 'true'

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with: 
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pytest
        env:
          LOCALSTACK_HOSTNAME: localhost
          AWS_ACCESS_KEY_ID: notARealAccessKey
          AWS_SECRET_ACCESS_KEY: notARealSecretKey
          AWS_DEFAULT_REGION: us-east-1
        run: uv run pytest tests